/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kolacer;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Scanner;

/**
 *
 * @author Kůň
 */
public class NacitacDat extends javax.swing.JDialog {
    
    private final String titleEnd, rowSplit;
    
    ArrayList<Udaj> udaje;
    String nadpis;
    boolean result;
    /**
     * Creates new form NacitacDat
     * @param parent
     * @param modal
     * @param titleEnd
     * @param rowEnd
     * 
     */
    public NacitacDat(java.awt.Frame parent, boolean modal, String titleEnd, String rowEnd) {
        super(parent, modal);
        this.setResizable(false);
        this.setTitle("Nacitac vysledku anket");
        this.setLocationRelativeTo(parent);
        result = false;
        initComponents();
        
        this.titleEnd = titleEnd;
        this.rowSplit = rowEnd;
        
        this.setLocation(parent.getX()+parent.getWidth()/2-this.getWidth()/2, parent.getY()+parent.getHeight()/2-this.getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTA_textObl = new javax.swing.JTextArea();
        jBut_Ok = new javax.swing.JButton();
        jBut_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTA_textObl.setColumns(20);
        jTA_textObl.setRows(5);
        jScrollPane1.setViewportView(jTA_textObl);

        jBut_Ok.setText("Potvrdit");
        jBut_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_OkActionPerformed(evt);
            }
        });

        jBut_Cancel.setText("Storno");
        jBut_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(406, Short.MAX_VALUE)
                .addComponent(jBut_Cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBut_Ok)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut_Ok)
                    .addComponent(jBut_Cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_OkActionPerformed
        boolean ulozenoSpravne = textNaUdaje();
        if(ulozenoSpravne){
            result = true;
            this.setVisible(false);
        }
        else
            jBut_Ok.setBackground(Color.red);
    }//GEN-LAST:event_jBut_OkActionPerformed

    private void jBut_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_CancelActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jBut_CancelActionPerformed

    public boolean showDialog(String textPrevod){
        if(textPrevod!=null){
            jTA_textObl.setText(textPrevod);
            return textNaUdaje();
        }
        else
            this.setVisible(true);
        return result;
    }
    private boolean textNaUdaje(){
        try{
            udaje = new ArrayList<>();
            Scanner sc = new Scanner(jTA_textObl.getText());
            nadpis = sc.nextLine().split(titleEnd)[0].trim();
            int cisloRadku = -1;
            while(sc.hasNextLine()){
                cisloRadku++;
                Udaj dalsi = radekNaUdaj(sc.nextLine());
                if(dalsi == null){
                    System.err.println(" na radku "+cisloRadku);
                }
                else
                    udaje.add(dalsi);
            }
            return true;
        }
        catch(Exception e){
            return false;
        }
    }
    private Udaj radekNaUdaj(String radek){
        String[] casti = radek.split(rowSplit);
        if(casti.length<2){
            System.err.print("Nebyl nalezen delici znak");
            return null;
        }
        String nazev = "";
        for(int i = 0; i<casti.length-1; i++)
            nazev+=casti[i] + ((i!=casti.length-2) ? rowSplit : "");
        
        int pocet;
        try ( Scanner sc = new Scanner(casti[casti.length-1]) ){
            pocet = sc.nextInt();
        }
        catch(NumberFormatException e){
            System.err.print("Chybi ciselna hodnota za posledni dvojteckou");
            return null;
        }
        return new Udaj(nazev, pocet, null);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_Cancel;
    private javax.swing.JButton jBut_Ok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTA_textObl;
    // End of variables declaration//GEN-END:variables

}
