/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kolacer;

import java.awt.Color;

/**
 *
 * @author Kůň
 */
public class VyberBarvy extends javax.swing.JDialog {

    Color result;
    /**
     * Creates new form VyberBarvy
     */
    public VyberBarvy(java.awt.Frame parent, boolean modal, boolean povolPruhl) {
        super(parent, modal);
        this.setResizable(false);
        result = null;
        this.setTitle("Výběr barvy");
        initComponents();
        this.setLocation(parent.getX()+parent.getWidth()/2-this.getWidth()/2, parent.getY()+parent.getHeight()/2-this.getHeight()/2);
        jBut_transparent.setVisible(povolPruhl);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCol_barva = new javax.swing.JColorChooser();
        jBut_potvrdit = new javax.swing.JButton();
        jBut_zrusit = new javax.swing.JButton();
        jBut_transparent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jCol_barva.setName(""); // NOI18N

        jBut_potvrdit.setText("Potvrdit");
        jBut_potvrdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_potvrditActionPerformed(evt);
            }
        });

        jBut_zrusit.setText("Zrusit");
        jBut_zrusit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_zrusitActionPerformed(evt);
            }
        });

        jBut_transparent.setText("Průhledná");
        jBut_transparent.setOpaque(false);
        jBut_transparent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_transparentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jBut_transparent)
                .addGap(51, 51, 51)
                .addComponent(jBut_zrusit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBut_potvrdit)
                .addGap(86, 86, 86))
            .addComponent(jCol_barva, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jCol_barva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBut_potvrdit)
                    .addComponent(jBut_zrusit)
                    .addComponent(jBut_transparent)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBut_potvrditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_potvrditActionPerformed
        result = jCol_barva.getColor();
        this.setVisible(false);
    }//GEN-LAST:event_jBut_potvrditActionPerformed

    private void jBut_zrusitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_zrusitActionPerformed
        result = null;
        this.setVisible(false);
    }//GEN-LAST:event_jBut_zrusitActionPerformed

    private void jBut_transparentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_transparentActionPerformed
        result = new Color(0,0,0,0);
        this.setVisible(false);
    }//GEN-LAST:event_jBut_transparentActionPerformed

    public Color showDialog(){
        this.setVisible(true);
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBut_potvrdit;
    private javax.swing.JButton jBut_transparent;
    private javax.swing.JButton jBut_zrusit;
    private javax.swing.JColorChooser jCol_barva;
    // End of variables declaration//GEN-END:variables
}
